language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4.0"
  #- "4.1"
  #- "4.2"
  #- "4.3"
  - "4.4"
  #- "5.0"
  #- "5.1"
  #- "5.10"
  #- "5.11"
  #- "5.2"
  #- "5.3"
  #- "5.4"
  #- "5.5"
  #- "5.6"
  #- "5.7"
  #- "5.8"
  - "5.9"
  - "6.0"
  - "6.1"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
